---

- name: Make sure we have a 'wheel' group
  group:
    name=wheel
    state=present
  tags:
    - deploy
    - ceph

- name: Allow wheel group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
  tags:
    - deploy
    - ceph

- name: Create ceph-deploy user
  user:
    name: ceph-deploy
    comment: Ceph Deploy user
    create_home: yes
    groups: wheel
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 1024
    ssh_key_file: .ssh/id_rsa
    state: present
  tags:
    - deploy
    - ceph

- name: copying over public key to ceph-deploy
  copy:
    src: roles/common/files/keys/ceph_admin.pub
    dest: /home/ceph-deploy/.ssh/authorized_keys
    owner: ceph-deploy
    mode: 0644
  tags:
    - deploy
    - ceph

- name: flush iptable rules
  iptables:
    flush: yes
  tags:
    - deploy
    - ceph
  when: ansible_distribution == "Ubuntu"

- name: add ceph iptable rule
  iptables:
    chain: INPUT
    in_interface: eth1
    protocol: tcp
    source: 10.0.0.0/24
    destination_port: 6789
    jump: ACCEPT
  become: yes
  tags:
    - deploy
    - ceph
  when: ansible_distribution == "Ubuntu"

#- name: Enable firewalld
#  service:
#    name: firewalld
#    state: started
#    enabled: yes
#  tags:
#    - deploy
#    - site
#  when: ansible_distribution == "Fedora"

#- name: Set dmz as default policy
#  command: firewall-cmd --set-default-zone=public
#  tags:
#    - deploy
#    - site
#  when: ansible_distribution == "Fedora"

#- name: (fedora) add etcd firewalld rule
#  firewalld:
#    zone: public
#    port: 6789/tcp
#    source: 10.0.0.0/24
#    permanent: true
#    immediate: true
#    state: enabled
#  become: yes
#  tags:
#    - deploy
#    - site
#  when: ansible_distribution == "Fedora"
