---

- name: Make ceph directory
  file:
    path: /home/ceph-admin/ceph-dir/
    owner: ceph-admin
    group: ceph-admin
    state: directory
    mode: 0775
  tags:
    - admin
    - ceph

- find:
    paths: /home/ceph-admin/ceph-dir/
    patterns: "*.*"
  register: files_to_delete
  tags:
    - admin
    - ceph

- name: Delete all files in ceph directory
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"
  tags:
    - admin
    - ceph

- name: Ceph Purge Nodes
  command: "ceph-deploy purge {{ hostvars[item]['ansible_hostname'] }}"
  args:
    chdir: /home/ceph-admin/ceph-dir/
  with_items: "{{ groups['nodes'] }}"
  become: yes
  become_user: ceph-admin
  tags:
    - admin
    - ceph

- name: Ceph Purge Data
  command: "ceph-deploy purgedata {{ hostvars[item]['ansible_hostname'] }}"
  args:
    chdir: /home/ceph-admin/ceph-dir/
  with_items: "{{ groups['nodes'] }}"
  become: yes
  become_user: ceph-admin
  tags:
    - admin
    - ceph

- name: Ceph Forget Keys
  command: "ceph-deploy forgetkeys"
  args:
    chdir: /home/ceph-admin/ceph-dir/
  become: yes
  become_user: ceph-admin
  tags:
    - admin
    - ceph

- name: Make configuration directory
  file:
    path: /etc/ceph/
    owner: root
    group: root
    state: directory
    mode: 0775
  tags:
    - admin
    - ceph

# We need to crete a configuration file for each ceph node
# http://docs.ceph.com/docs/giant/rados/configuration/ceph-conf/
- name: copy ceph configuration template to each node
  template:
    src: roles/common/templates/ceph.j2
    dest: /etc/ceph/ceph.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - admin
    - ceph
    - common

- name: Create Ceph Nodes
  command: "ceph-deploy new {{ hostvars[item]['ansible_hostname'] }}"
  args:
    chdir: /home/ceph-admin/ceph-dir/
  with_items: "{{ groups['deploy'] }}"
  become: yes
  become_user: ceph-admin
  tags:
    - admin
    - ceph

- name: Install Ceph Node Packages
  command: "ceph-deploy install {{ hostvars[item]['ansible_hostname'] }}"
  args:
    chdir: /home/ceph-admin/ceph-dir/
  with_items: "{{ groups['nodes'] }}"
  become: yes
  become_user: ceph-admin
  tags:
    - admin
    - ceph
  when: ansible_distribution == "Ubuntu"

- name: (fedora) Install Ceph Node Packages
  command: "ceph-deploy install --no-adjust-repos {{ hostvars[item]['ansible_hostname'] }}"
  args:
    chdir: /home/ceph-admin/ceph-dir/
  with_items: "{{ groups['nodes'] }}"
  become: yes
  become_user: ceph-admin
  tags:
    - admin
    - ceph
  when: ansible_distribution == "Fedora"

- name: Create Ceph Monitor
  command: "ceph-deploy mon create-initial"
  args:
    chdir: /home/ceph-admin/ceph-dir/
  become: yes
  become_user: ceph-admin
  tags:
    - admin
    - ceph

- name: Copy admin configuration/files to Nodes
  command: "ceph-deploy admin {{ hostvars[item]['ansible_hostname'] }}"
  args:
    chdir: /home/ceph-admin/ceph-dir/
  with_items: "{{ groups['nodes'] }}"
  become: yes
  become_user: ceph-admin
  tags:
    - admin
    - ceph

# btrfs also incorporates multi-device management into the file system, which
# enables you to support heterogeneous disk storage infrastructure, data allocation
# policies. The community also aims to provide fsck, deduplication, and data
# encryption support in the future. This compelling list of features makes btrfs
# the ideal choice for Ceph clusters.
# http://docs.ceph.com/docs/jewel/rados/configuration/filesystem-recommendations/
- name: Create OSDs - this will take a while...
  command: "ceph-deploy osd create --zap-disk --fs-type xfs {{ hostvars[item]['ansible_hostname'] }}:/dev/vdb"
  args:
    chdir: /home/ceph-admin/ceph-dir/
  with_items: "{{ groups['deploy'] }}"
  become: yes
  become_user: ceph-admin
  tags:
    - admin
    - ceph

# we dont need a meta data server on every node.  These are used for cephfs
- name: Create Metadata Server
  command: "ceph-deploy mds create {{ item }}"
  args:
    chdir: /home/ceph-admin/ceph-dir/
  with_items:
    - "ceph0"
    - "ceph2"
  become: yes
  become_user: ceph-admin
  tags:
    - admin
    - ceph

# check quorum with `ceph quorum_status --format json-pretty` on cephX nodes
# should be odd, min 3. As we have 4 nodes, we will settle with 3
- name: Create a ceph monitors (3 for HA)
  command: "ceph-deploy mon add {{ item }}"
  args:
    chdir: /home/ceph-admin/ceph-dir/
  with_items:
    - "ceph0"
    - "ceph1"
    - "ceph2"
  become: yes
  become_user: ceph-admin
  tags:
    - admin
    - ceph

# Add Object Gateway, default web interface on 7480
- name: Create a RGW
  command: "ceph-deploy rgw create {{ item }}"
  args:
    chdir: /home/ceph-admin/ceph-dir/
  with_items:
    - "ceph1"
  become: yes
  become_user: ceph-admin
  tags:
    - admin
    - ceph
