---

- name: Install ceph key
  apt_key:
    url: https://download.ceph.com/keys/release.asc
    state: present
  tags:
    - admin
    - ceph
  when: ansible_distribution == "Ubuntu"

- name: Install ceph-deploy
  apt:
    state: latest
  with_items:
    - ceph-deploy
    - ntp
  tags:
    - admin
    - ceph
  when: ansible_distribution == "Ubuntu"

- name: "dnf install packages"
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - ceph-deploy
    - ntp
    - ntpdate
    - ntp-doc
  tags:
    - admin
    - ceph
  when: ansible_distribution == "Fedora"

- name: (fedora) Get latest ceph-deploy
  command: "pip3 install ceph-deploy"
  become: yes
  tags:
    - admin
    - ceph
  when: ansible_distribution == "Fedora"

- name: (fedora) create symbolic link to ceph-deploy
  command: "sudo ln -sf /usr/local/bin/ceph-deploy /usr/bin/ceph-deploy"
  become: yes
  tags:
    - admin
    - ceph
  when: ansible_distribution == "Fedora"

- name: Make sure we have a 'wheel' group
  group:
    name=wheel
    state=present
  tags:
    - admin
    - ceph

- name: Allow wheel group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
  tags:
    - admin
    - ceph

- name: Create ceph-admin user
  user:
    name: ceph-admin
    comment: Ceph Admin Worker
    create_home: yes
    groups: wheel
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 1024
    ssh_key_file: .ssh/id_rsa
    state: present
  tags:
    - admin
    - ceph

- name: copying over private key to ceph-admin
  copy:
    src: roles/common/files/keys/ceph_admin
    dest: /home/ceph-admin/.ssh/id_rsa
    owner: ceph-admin
    group: ceph-admin
    mode: 0600
  tags:
    - admin
    - ceph

- name: copying over public key to ceph-admin
  copy:
    src: roles/common/files/keys/ceph_admin.pub
    dest: /home/ceph-admin/.ssh/id_rsa.pub
    owner: ceph-admin
    group: ceph-admin
    mode: 0644
  tags:
    - admin
    - ceph

- name: copy host file to admin server
  template:
    src: roles/admin/templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags:
    - admin
    - ceph

- name: copy ssh config file to admin server
  template:
    src: roles/admin/templates/config.j2
    dest: /home/ceph-admin/.ssh/config
    owner: ceph-admin
    group: ceph-admin
    mode: 0644
  tags:
    - admin
    - ceph

- name: flush iptable rules
  iptables:
    flush: yes
  tags:
    - admin
    - ceph
  when: ansible_distribution == "Ubuntu"

- name: add ceph iptable rule
  iptables:
    chain: INPUT
    in_interface: eth1
    protocol: tcp
    source: 10.0.0.0/24
    destination_port: 6789
    jump: ACCEPT
  become: yes
  tags:
    - admin
    - ceph
  when: ansible_distribution == "Ubuntu"

- name: Enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  tags:
    - admin
    - ceph
  when: ansible_distribution == "Fedora"

- name: Set dmz as default policy
  command: firewall-cmd --set-default-zone=public
  tags:
    - admin
    - ceph
  when: ansible_distribution == "Fedora"

- name: (fedora) add etcd firewalld rule
  firewalld:
    zone: public
    port: 6789/tcp
    source: 10.0.0.0/24
    permanent: true
    immediate: true
    state: enabled
  become: yes
  tags:
    - admin
    - site
  when: ansible_distribution == "Fedora"

- name: create & wipe contents of known_hosts file
  copy:
    content: ""
    dest: /home/ceph-admin/.ssh/known_hosts
    force: yes
    owner: ceph-admin
    group: ceph-admin
    mode: 0644
  tags:
    - admin
    - site

- name: run ssh-keyscan to add keys to known_hosts for eth0
  shell: "ssh-keyscan -H {{ hostvars[item]['ansible_hostname'] }} >> /home/ceph-admin/.ssh/known_hosts"
  with_items: "{{ groups['nodes'] }}"
  tags:
    - admin
    - site

# this requires the precheck.yml to configure ceph_ip eth1 interfaces for ansible variable
- name: run ssh-keyscan to add keys to known_hosts for eth1
  shell: "ssh-keyscan -H {{ hostvars[item]['ceph_ip'] }} >> /home/ceph-admin/.ssh/known_hosts"
  with_items: "{{ groups['nodes'] }}"
  tags:
    - admin
    - site
