---

- name: Make sure we have a 'wheel' group
  group:
    name=wheel
    state=present
  tags:
    - admin
    - ceph

- name: Allow wheel group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
  tags:
    - admin
    - ceph

- name: Create ceph-deploy user
  user:
    name: ceph-deploy
    comment: Ceph Admin Worker
    create_home: yes
    groups: wheel
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    state: present
  tags:
    - admin
    - ceph

- name: copying over private key to ceph-deploy
  copy:
    src: roles/common/files/keys/ceph_admin
    dest: /home/ceph-deploy/.ssh/id_rsa
    owner: ceph-deploy
    group: ceph-deploy
    mode: 0600
  tags:
    - admin
    - ceph

- name: copying over public key to ceph-deploy
  copy:
    src: roles/common/files/keys/ceph_admin.pub
    dest: /home/ceph-deploy/.ssh/id_rsa.pub
    owner: ceph-deploy
    group: ceph-deploy
    mode: 0644
  tags:
    - admin
    - ceph

- name: copy ssh config file to admin server
  template:
    src: roles/admin/templates/config.j2
    dest: /home/ceph-deploy/.ssh/config
    owner: ceph-deploy
    group: ceph-deploy
    mode: 0644
  tags:
    - admin
    - ceph

- name: flush iptable rules
  iptables:
    flush: yes
  tags:
    - admin
    - ceph
  when: ansible_distribution == "Ubuntu"

- name: add ceph iptable rule
  iptables:
    chain: INPUT
    in_interface: eth1
    protocol: tcp
    source: 10.0.0.0/24
    destination_port: 6789
    jump: ACCEPT
  become: yes
  tags:
    - admin
    - ceph
  when: ansible_distribution == "Ubuntu"

#- name: Enable firewalld
#  service:
#    name: firewalld
#    state: started
#    enabled: yes
#  tags:
#    - admin
#    - ceph
#  when: ansible_distribution == "Fedora"

#- name: Set dmz as default policy
#  command: firewall-cmd --set-default-zone=public
#  tags:
#    - admin
#    - ceph
#  when: ansible_distribution == "Fedora"

#- name: (fedora) add etcd firewalld rule
#  firewalld:
#    zone: public
#    port: 6789/tcp
#    source: 10.0.0.0/24
#    permanent: true
#    immediate: true
#    state: enabled
#  become: yes
#  tags:
#    - admin
#    - site
#  when: ansible_distribution == "Fedora"

- name: create & wipe contents of known_hosts file
  copy:
    content: ""
    dest: /home/ceph-deploy/.ssh/known_hosts
    force: yes
    owner: ceph-deploy
    group: ceph-deploy
    mode: 0644
  tags:
    - admin
    - site
    - test

- name: run ssh-keyscan to add keys to known_hosts for ceph hosts
  shell: "ssh-keyscan -H {{ hostvars[item]['ansible_hostname'] }} >> /home/ceph-deploy/.ssh/known_hosts"
  become: ceph-deploy
  with_items: "{{ groups['nodes'] }}"
  tags:
    - admin
    - site
    - test

- name: run ssh-keyscan to add keys to known_hosts for ceph ips
  shell: "ssh-keyscan -H {{ hostvars[item]['ceph_ip'] }} >> /home/ceph-deploy/.ssh/known_hosts"
  become: ceph-deploy
  with_items: "{{ groups['nodes'] }}"
  tags:
    - admin
    - site
    - test
