---

- name: Install ceph key
  apt_key:
    url: https://download.ceph.com/keys/release.asc
    state: present

- name: Install ceph-deploy
  apt:
    name: "ceph-deploy"
    state: latest

- name: Make sure we have a 'wheel' group
  group:
    name=wheel
    state=present

- name: Allow wheel group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Create ceph-admin user
  user:
    name: ceph-admin
    comment: Ceph Admin Worker
    create_home: yes
    groups: wheel
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 1024
    ssh_key_file: .ssh/id_rsa
    state: present

- name: copying over private key to ceph-admin
  copy:
    src: roles/common/files/keys/ceph_admin
    dest: /home/ceph-admin/.ssh/id_rsa
    owner: ceph-admin
    group: ceph-admin
    mode: 0600

- name: copying over public key to ceph-admin
  copy:
    src: roles/common/files/keys/ceph_admin.pub
    dest: /home/ceph-admin/.ssh/id_rsa.pub
    owner: ceph-admin
    group: ceph-admin
    mode: 0644

- name: copy host file to admin server
  template:
    src: roles/admin/templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: copy ssh config file to admin server
  template:
    src: roles/admin/templates/config.j2
    dest: /home/ceph-admin/.ssh/config
    owner: ceph-admin
    group: ceph-admin
    mode: 0644

- name: flush iptable rules
  iptables:
    flush: yes

- name: add ceph iptable rule
  iptables:
    chain: INPUT
    in_interface: eth1
    protocol: tcp
    source: 10.0.0.0/24
    destination_port: 6789
    jump: ACCEPT
  become: yes

- name: create & wipe contents of known_hosts file
  copy:
    content: ""
    dest: /home/ceph-admin/.ssh/known_hosts
    force: yes
    owner: ceph-admin
    group: ceph-admin
    mode: 0644

- name: run ssh-keyscan to add keys to known_hosts for eth0
  shell: "ssh-keyscan -H {{ hostvars[item]['ansible_hostname'] }} >> /home/ceph-admin/.ssh/known_hosts"
  with_items: "{{ groups['deploy'] }}"

# this requires the precheck.yml to configure ceph_ip eth1 interfaces for ansible variable
- name: run ssh-keyscan to add keys to known_hosts for eth1
  shell: "ssh-keyscan -H {{ hostvars[item]['ceph_ip'] }} >> /home/ceph-admin/.ssh/known_hosts"
  with_items: "{{ groups['deploy'] }}"

#- name: write ssh to known_hosts
#lineinfile:
#  dest: /home/ceph-admin/.ssh/known_hosts
#  line: "{{ item.stdout }}"
#  insertafter: EOF
#with_items: "{{ test.results }}"
