- name: install ceph packages
  import_tasks: install_packages.yml

- name: get ceph ready for deploy
  import_tasks: install_ceph.yml

- name: deploy ceph cluster
  import_tasks: deploy_ceph.yml

- name: test ceph cluster
  import_tasks: test_ceph.yml
