---

- name: "apt-get update"
  apt:
    update_cache: yes
  tags:
    - database
    - site
  when: ansible_distribution == "Ubuntu"

- name: wget etcd 3.3.9
  get_url:
    url: https://github.com/etcd-io/etcd/releases/download/v3.3.9/etcd-v3.3.9-linux-amd64.tar.gz
    dest: /root/etcd-v3.3.9-linux-amd64.tar.gz
    checksum: sha256:7b95bdc6dfd1d805f650ea8f886fdae6e7322f886a8e9d1b0d14603767d053b1
  become: yes
  tags:
    - database
    - site

- name: create etcd stuff
  file:
    path: /root/etcd
    owner: root
    group: root
    state: directory
    mode: 0775
  become: yes
  tags:
    - database
    - site

- name: (fedora) create etcd dir
  file:
    path: /root/etcd-v3.3.9-linux-amd64
    owner: root
    group: root
    state: directory
    mode: 0775
  become: yes
  tags:
    - database
    - site
  when: ansible_distribution == "Fedora"

- name: Extract etcd
  unarchive:
    src: /root/etcd-v3.3.9-linux-amd64.tar.gz
    dest: /root/etcd-v3.3.9-linux-amd64
    remote_src: yes
  become: yes
  tags:
    - database
    - site

- name: copy etcd to /usr/bin
  copy:
    src: /root/etcd-v3.3.9-linux-amd64/etcd
    dest: /usr/bin/
    mode: 0755
    remote_src: yes
  become: yes
  tags:
    - database
    - site
  when: ansible_distribution == "Ubuntu"

- name: (fedora) copy etcd to /usr/bin
  copy:
    src: /root/etcd-v3.3.9-linux-amd64/etcd-v3.3.9-linux-amd64/etcd
    dest: /usr/bin/
    mode: 0755
    remote_src: yes
  become: yes
  tags:
    - database
    - site
  when: ansible_distribution == "Fedora"

- name: copy etcdctl to /usr/bin
  copy:
    src: /root/etcd-v3.3.9-linux-amd64/etcd-v3.3.9-linux-amd64/etcdctl
    dest: /usr/bin/
    mode: 0755
    remote_src: yes
  become: yes
  tags:
    - database
    - site
  when: ansible_distribution == "Fedora"

- name: (fedora) copy etcdctl to /usr/bin
  copy:
    src: /root/etcd-v3.3.9-linux-amd64/etcdctl
    dest: /usr/bin/
    mode: 0755
    remote_src: yes
  become: yes
  tags:
    - database
    - site
  when: ansible_distribution == "Ubuntu"

- name: stop database service
  systemd:
    state: started
    enabled: False
    name: etcd
  ignore_errors: yes
  tags:
    - database
    - site

- name: "kill etcd instances"
  shell: killall etcd
  become: yes
  ignore_errors: yes
  tags:
    - database
    - site

- name: remove etcd2 service install by apt
  file:
    path: /etc/systemd/system/etcd2.service
    state: absent
  become: yes
  tags:
    - database
    - site

- name: flush iptable rules
  iptables:
    flush: yes
  tags:
    - database
    - site
  when: ansible_distribution == "Ubuntu"

- name: add etcd iptable rule
  iptables:
    chain: INPUT
    in_interface: eth1
    protocol: tcp
    source: 10.0.0.0/24
    destination_port: 2379:2380
    jump: ACCEPT
  become: yes
  tags:
    - database
    - site
  when: ansible_distribution == "Ubuntu"

#- name: Enable firewalld
#  service:
#    name: firewalld
#    state: started
#    enabled: yes
#  when: ansible_distribution == "Fedora"

#- name: Set dmz as default policy
#  command: firewall-cmd --set-default-zone=public
#  when: ansible_distribution == "Fedora"

#- name: (fedora) add etcd firewalld rule
#  firewalld:
#    zone: public
#    port: 2379-2380/tcp
#    source: 10.0.0.0/24
#    permanent: true
#   immediate: true
#    state: enabled
#  become: yes
#  tags:
#    - database
#    - site
#  when: ansible_distribution == "Fedora"

- name: copy systemd file to database
  template:
    src: roles/database/templates/etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
  become: yes
  tags:
    - database
    - site

- name: start database (etcd) service
  systemd:
    state: started
    enabled: True
    name: etcd
  tags:
    - database
    - site

- name: restart database (etcd) to pick up daemon changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: etcd
  tags:
    - database
    - site

- name: "Destroy database if it exists"
  shell: etcdctl del --prefix=true /
  become: yes
  environment:
    ETCDCTL_API: 3
  tags:
    - database
    - site
