---

- name: install ceph filesystem packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - ceph-fs-common
      - ceph-fuse
  tags:
    - app
    - ceph
  when: ansible_distribution == "Ubuntu"

- name: install ceph filesystem packages
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
      - ceph-common
      - ceph-fuse
  tags:
    - app
    - ceph
  when: ansible_distribution == "Fedora"

# We need to crete a configuration file for each ceph node
# http://docs.ceph.com/docs/giant/rados/configuration/ceph-conf/
- name: copy ceph configuration
  template:
    src: roles/common/templates/ceph.j2
    dest: /etc/ceph/ceph.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - app
    - ceph

- name: create pool list name
  set_fact:
    ceph_fs_pools:
      - "cephfs-data"
      - "cephfs-metadata"
  tags:
    - app
    - ceph

# placement group calculation: http://docs.ceph.com/docs/jewel/rados/operations/placement-groups/#preselection
- name: create pools for filesystem
  command: "ceph osd pool create {{ item }} 1024 replicated"
  with_items: "{{ ceph_fs_pools }}"
  become_user: ceph-deploy
  tags:
    - app
    - ceph

- name: create filesystem using pools
  command: "ceph fs new test_filesystem {{ item }}"
  with_items:
    - "{{ ceph_fs_pools | join(' ') }}"
  become_user: ceph-deploy
  tags:
    - app
    - ceph

- name: create filesystem mount point
  file:
    path: /mnt/cephfs/
    owner: root
    group: root
    state: directory
    mode: 0775
  tags:
    - app
    - ceph

- name: get monitors
  shell: ceph mon dump 2>&1 | grep "mon\." | cut -d " " -f 2 | cut -d "/" -f 1
  register: get_mons
  tags:
    - app
    - ceph

- name: get secret token
  shell: cat /etc/ceph/ceph.client.admin.keyring | tail -n1 | sed 's/ //g' | cut -d "=" -f 2-
  register: secret
  tags:
    - app
    - ceph

- name: create secret token file
  file:
    path: /etc/ceph/secret
    mode: 0700
    owner: root
    group: root
    state: touch
  tags:
    - app
    - ceph

- name: copy secret
  copy:
    dest: /etc/ceph/secret
    content: "{{ secret.stdout }}"
  tags:
    - app
    - ceph

- name: create filesystem using pools
  command: "sudo mount -t ceph {{ get_mons.stdout_lines[0] }}:/ /mnt/cephfs -o name=admin,secretfile=/etc/ceph/secret"
  become_user: ceph-deploy
  become: yes
  tags:
    - app
    - ceph
