---

- name: "apt-get update"
  apt:
    update_cache: yes
  tags:
    - commander
    - site
  when: ansible_distribution == "Ubuntu"

- name: "apt-get install packages"
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - etcd
    - git
    - libprotoc-dev
    - protobuf-compiler
    - make
  tags:
    - commander
    - site
  when: ansible_distribution == "Ubuntu"

- name: "dnf install packages"
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - etcd
    - git
    - make
  tags:
    - commander
    - site
  when: ansible_distribution == "Fedora"



- name: delete all go stuff
  file:
    path: /root/go/
    state: absent
  become: yes
  tags:
    - commander
    - site

- name: delete all gosrc stuff
  file:
    path: /root/gosrc
    state: absent
  become: yes
  tags:
    - commander
    - site

- name: delete all go.gz stuff
  file:
    path: /root/go*.gz
    state: absent
  become: yes
  tags:
    - commander
    - site

- name: get golang 1.10.3
  get_url:
    url: https://dl.google.com/go/go1.11.1.linux-amd64.tar.gz
    dest: /root/go1.11.1.linux-amd64.tar.gz
    checksum: sha256:2871270d8ff0c8c69f161aaae42f9f28739855ff5c5204752a8d92a1c9f63993
  become: yes
  tags:
    - commander
    - site

- name: create gosrc stuff
  file:
    path: /root/gosrc
    owner: root
    group: root
    state: directory
    mode: 0775
  become: yes
  tags:
    - commander
    - site


- name: Extract golang
  unarchive:
    src: /root/go1.11.1.linux-amd64.tar.gz
    dest: /root/gosrc/
    remote_src: yes
  become: yes
  tags:
    - commander
    - site

- name: copy go to /usr/bin
  copy:
    src: /root/gosrc/go/bin/go
    dest: /usr/bin/go
    mode: 0755
    remote_src: yes
  become: yes
  tags:
    - commander
    - site

- name: stop commander (napoleon) service
  systemd:
    state: started
    enabled: False
    name: napoleon
  ignore_errors: yes
  tags:
    - commander
    - site

- name: "kill commander"
  shell: killall commander
  ignore_errors: yes
  become: yes
  tags:
    - commander
    - site

- name: "kill etcd instances"
  shell: killall etcd
  ignore_errors: yes
  become: yes
  tags:
    - commander
    - site

- name: "kill golang instances"
  shell: killall golang
  ignore_errors: yes
  become: yes
  tags:
    - commander
    - site

- name: flush iptable rules
  iptables:
    flush: yes
  tags:
    - commander
    - site

- name: add etcd iptable rule
  iptables:
    chain: INPUT
    in_interface: eth1
    protocol: tcp
    source: 10.0.0.0/24
    destination_port: 2379:2380
    jump: ACCEPT
  become: yes
  tags:
    - commander
    - site

- name: copy host file to commander
  template:
    src: roles/commander/templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  become: yes
  tags:
    - commander
    - site

- name: create go stuff
  file:
    path: /root/go/src/gitlab.com/mergetb/
    owner: root
    group: root
    state: directory
    mode: 0775
  become: yes
  tags:
    - commander
    - site

- name: get latest commander code
  git:
    repo: 'https://gitlab.com/mergetb/site.git'
    dest: /root/go/src/gitlab.com/mergetb/site
    clone: yes
    update: yes
  become: yes
  tags:
    - commander
    - site

- name: get protobuf
  shell: go get -u github.com/golang/protobuf/protoc-gen-go
  environment:
    GOPATH: /root/go/
    GOROOT: /root/gosrc/go
  become: yes
  tags:
    - commander
    - site

- name: get dep
  shell: go get -u github.com/golang/dep/cmd/dep
  environment:
    GOPATH: /root/go/
    GOROOT: /root/gosrc/go
  become: yes
  tags:
    - commander
    - site

- name: dep ensure
  shell: $GOBIN/dep ensure -v
  args:
    chdir: /root/go/src/gitlab.com/mergetb/site
  environment:
    GOPATH: /root/go/
    GOROOT: /root/gosrc/go
    GOBIN: /root/go/bin
  become: yes
  tags:
    - commander
    - site

- name: make commander
  make:
    chdir: /root/go/src/gitlab.com/mergetb/site
    target: all
  become: yes
  environment:
    GOPATH: /root/go/
    GOROOT: /root/gosrc/go
  tags:
    - commander
    - site

- name: move commander to /usr/bin
  copy:
    src: /root/go/src/gitlab.com/mergetb/site/build/commander
    dest: /usr/bin/commander
    mode: 0755
    remote_src: yes
  become: yes
  tags:
    - commander
    - site

- name: copy systemd file to commander
  template:
    src: roles/commander/templates/napoleon.service.j2
    dest: /etc/systemd/system/napoleon.service
    owner: root
    group: root
  become: yes
  tags:
    - commander
    - site

- name: start commander (napoleon) service
  systemd:
    state: started
    enabled: True
    name: napoleon
  tags:
    - commander
    - site

- name: restart commander (napoleon) to pick up daemon changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: napoleon
  tags:
    - commander
    - site
