---

- name: copy host file to all nodes
  template:
    src: roles/common/templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags:
    - admin
    - common
    - hosts
