---

- name: "dnf install packages"
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - etcd
    - git
    - make
    - gcc
    - librados-devel
    - librbd-devel
    - libcephfs-devel
    - unzip
    - zip
    - protobuf
    - protobuf-compiler
  tags:
    - agent
    - site
  when: ansible_distribution == "Fedora"

- name: delete all protobuf stuff
  file:
    path: /root/protoc*
    state: absent
  become: yes
  tags:
    - agent
    - site

- name: get protobuf3
  get_url:
    url: https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
    dest: /root/protoc-3.6.1-linux-x86_64.zip
    checksum: sha256:6003de742ea3fcf703cfec1cd4a3380fd143081a2eb0e559065563496af27807
  become: yes
  tags:
    - agent
    - site

- name: create protoc stuff
  file:
    path: /root/protoc
    owner: root
    group: root
    state: directory
    mode: 0775
  become: yes
  tags:
    - agent
    - site

- name: Extract protobuf
  unarchive:
    src: /root/protoc-3.6.1-linux-x86_64.zip
    dest: /root/protoc
    remote_src: yes
  become: yes
  tags:
    - agent
    - site

- name: stop driver (Josephine) service
  systemd:
    state: stopped
    enabled: False
    name: josephine
  ignore_errors: yes
  tags:
    - agent
    - site

- name: stop sled agent
  systemd:
    state: stopped
    enabled: False
    name: sled
  ignore_errors: yes
  tags:
    - agent
    - site

- name: stop etcd
  systemd:
    state: stopped
    enabled: False
    name: etcd
  ignore_errors: yes
  tags:
    - agent
    - site

- name: "kill driver"
  shell: pkill driver
  ignore_errors: yes
  become: yes
  tags:
    - agent
    - site

- name: "kill sled"
  shell: pkill sled
  ignore_errors: yes
  become: yes
  tags:
    - agent
    - site

- name: "kill golang instances"
  shell: pkill golang
  ignore_errors: yes
  become: yes
  tags:
    - agent
    - site

- name: copy protobuf to /usr/bin
  copy:
    src: /root/protoc/bin/protoc
    dest: /usr/bin/
    mode: 0755
    remote_src: yes
  become: yes
  tags:
    - agent
    - site

# ansible sucks sometimes.
- name: copy protobuf to /usr/bin
  command: sudo cp -r /root/protoc/include/ /usr/local/include/
  become: yes
  tags:
    - agent
    - site

- name: delete all go stuff
  file:
    path: /root/go/
    state: absent
  become: yes
  tags:
    - agent
    - site

- name: delete all gosrc stuff
  file:
    path: /root/gosrc
    state: absent
  become: yes
  tags:
    - agent
    - site

- name: delete all go.gz stuff
  file:
    path: /root/go*.gz
    state: absent
  become: yes
  tags:
    - agent
    - site

- name: get golang 1.11.1
  get_url:
    url: https://dl.google.com/go/go1.11.1.linux-amd64.tar.gz
    dest: /root/go1.11.1.linux-amd64.tar.gz
    checksum: sha256:2871270d8ff0c8c69f161aaae42f9f28739855ff5c5204752a8d92a1c9f63993
  become: yes
  tags:
    - agent
    - site

- name: create gosrc stuff
  file:
    path: /root/gosrc
    owner: root
    group: root
    state: directory
    mode: 0775
  become: yes
  tags:
    - agent
    - site

- name: Extract golang
  unarchive:
    src: /root/go1.11.1.linux-amd64.tar.gz
    dest: /root/gosrc/
    remote_src: yes
  become: yes
  tags:
    - agent
    - site

- name: copy go to /usr/bin
  copy:
    src: /root/gosrc/go/bin/go
    dest: /usr/bin/go
    mode: 0755
    remote_src: yes
  become: yes
  tags:
    - agent
    - site

- name: copy host file to agent
  template:
    src: roles/driver/templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  become: yes
  tags:
    - agent
    - site

- name: create go stuff
  file:
    path: /root/go/src/gitlab.com/mergetb/
    owner: root
    group: root
    state: directory
    mode: 0775
  become: yes
  tags:
    - agent
    - site

- name: get latest agent code
  git:
    repo: 'https://gitlab.com/dcomptb/agents.git'
    dest: /root/go/src/gitlab.com/dcomptb/agents
    clone: yes
    update: yes
  become: yes
  tags:
    - agent
    - site

- name: get go-protobuf
  shell: go get github.com/ceph/go-ceph
  environment:
    GOPATH: /root/go/
    GOBIN: /root/go/bin
    GOROOT: /root/gosrc/go
  become: yes
  tags:
    - agent
    - site

- name: get go-protobuf
  shell: go get -u github.com/golang/protobuf/protoc-gen-go
  environment:
    GOPATH: /root/go/
    GOBIN: /root/go/bin
    GOROOT: /root/gosrc/go
  become: yes
  tags:
    - agent
    - site

- name: get dep
  shell: go get -u github.com/golang/dep/cmd/dep
  environment:
    GOPATH: /root/go/
    GOROOT: /root/gosrc/go
  become: yes
  tags:
    - agent
    - site

- name: dep ensure
  shell: $GOBIN/dep ensure -v
  args:
    chdir: /root/go/src/gitlab.com/dcomptb/agents
  environment:
    GOPATH: /root/go/
    GOROOT: /root/gosrc/go
    GOBIN: /root/go/bin
  become: yes
  tags:
    - agent
    - site

- name: set path variable
  set_fact:
    path_var:  "{{ lookup('env','PATH') }}"
  tags:
    - agent
    - site

- name: make driver
  make:
    chdir: /root/go/src/gitlab.com/dcomptb/agents
    target: all
  become: yes
  environment:
    GOPATH: /root/go/
    GOROOT: /root/gosrc/go
    PATH: "{{ path_var }}:/root/go/bin"
  tags:
    - agent
    - site

- name: move driver to /usr/bin
  copy:
    src: /root/go/src/gitlab.com/dcomptb/agents/build/driver
    dest: /usr/bin/driver
    mode: 0755
    remote_src: yes
  become: yes
  tags:
    - agent
    - site

- name: create merge directory
  file:
    path: /etc/merge
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - agent
    - site

- name: copying over merge db config file
  copy:
    src: roles/driver/files/merge.yml
    dest: /etc/merge/merge.yml
    owner: root
    group: root
    mode: 0644
  tags:
    - agent
    - site

- name: copy systemd file to agent
  template:
    src: roles/driver/templates/josephine.service.j2
    dest: /etc/systemd/system/josephine.service
    owner: root
    group: root
  become: yes
  tags:
    - agent
    - site

- name: start driver (josephine) service
  systemd:
    state: started
    enabled: True
    name: josephine
  tags:
    - agent
    - site

- name: restart driver (josephine) to pick up daemon changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: josephine
  tags:
    - agent
    - site

- name: move sled agent to /usr/bin
  copy:
    src: /root/go/src/gitlab.com/dcomptb/agents/build/sled
    dest: /usr/bin/sled
    mode: 0755
    remote_src: yes
  become: yes
  tags:
    - agent
    - site

- name: copy systemd file to sled
  template:
    src: roles/driver/templates/sled.service.j2
    dest: /etc/systemd/system/sled.service
    owner: root
    group: root
  become: yes
  tags:
    - agent
    - site

- name: start sled service
  systemd:
    state: started
    enabled: True
    name: sled
  tags:
    - agent
    - site

- name: restart sled to pick up daemon changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: sled
  tags:
    - agent
    - site

- name: copy test script to agent
  copy:
    src: roles/driver/files/test.sh
    dest: /root/test.sh
    owner: root
    group: root
    mode: 0755
  become: yes
  tags:
    - agent
    - site
