---

- name: "apt-get update"
  apt:
    update_cache: yes
  tags:
    - driver
    - site
  when: ansible_distribution == "Ubuntu"

- name: "apt-get upgrade"
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - etcd
    - git
    - libprotoc-dev
    - make
    - gcc
    - librados-dev # librados2-devel
    - librbd-dev
    - libcephfs-dev
  tags:
    - driver
    - site
  when: ansible_distribution == "Ubuntu"

- name: "dnf install packages"
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - etcd
    - git
    - make
    - gcc
    - librados-devel
    - librbd-devel
    - libcephfs-devel
    - unzip
    - zip
  tags:
    - driver
    - site
  when: ansible_distribution == "Fedora"

- name: delete all protobuf stuff
  file:
    path: /root/protoc*
    state: absent
  become: yes
  tags:
    - driver
    - site

- name: get protobuf3
  get_url:
    url: https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
    dest: /root/protoc-3.6.1-linux-x86_64.zip
    checksum: sha256:6003de742ea3fcf703cfec1cd4a3380fd143081a2eb0e559065563496af27807
  become: yes
  tags:
    - driver
    - site

- name: create protoc stuff
  file:
    path: /root/protoc
    owner: root
    group: root
    state: directory
    mode: 0775
  become: yes
  tags:
    - driver
    - site

- name: Extract protobuf
  unarchive:
    src: /root/protoc-3.6.1-linux-x86_64.zip
    dest: /root/protoc
    remote_src: yes
  become: yes
  tags:
    - driver
    - site

- name: copy protobuf to /usr/bin
  copy:
    src: /root/protoc/bin/protoc
    dest: /usr/bin/
    mode: 0755
    remote_src: yes
  become: yes
  tags:
    - driver
    - site

# ansible sucks sometimes.
- name: copy protobuf to /usr/bin
  command: sudo cp -r /root/protoc/include/ /usr/local/include/
  become: yes
  tags:
    - driver
    - site

- name: delete all go stuff
  file:
    path: /root/go/
    state: absent
  become: yes
  tags:
    - driver
    - site

- name: delete all gosrc stuff
  file:
    path: /root/gosrc
    state: absent
  become: yes
  tags:
    - driver
    - site

- name: delete all go.gz stuff
  file:
    path: /root/go*.gz
    state: absent
  become: yes
  tags:
    - driver
    - site

- name: get golang 1.11.1
  get_url:
    url: https://dl.google.com/go/go1.11.1.linux-amd64.tar.gz
    dest: /root/go1.11.1.linux-amd64.tar.gz
    checksum: sha256:2871270d8ff0c8c69f161aaae42f9f28739855ff5c5204752a8d92a1c9f63993
  become: yes
  tags:
    - driver
    - site

- name: create gosrc stuff
  file:
    path: /root/gosrc
    owner: root
    group: root
    state: directory
    mode: 0775
  become: yes
  tags:
    - driver
    - site

- name: Extract golang
  unarchive:
    src: /root/go1.11.1.linux-amd64.tar.gz
    dest: /root/gosrc/
    remote_src: yes
  become: yes
  tags:
    - driver
    - site

- name: copy go to /usr/bin
  copy:
    src: /root/gosrc/go/bin/go
    dest: /usr/bin/go
    mode: 0755
    remote_src: yes
  become: yes
  tags:
    - driver
    - site

- name: stop driver (Josephine) service
  systemd:
    state: started
    enabled: False
    name: josephine
  ignore_errors: yes
  tags:
    - driver
    - site

- name: "kill driver"
  shell: killall driver
  ignore_errors: yes
  become: yes
  tags:
    - driver
    - site

- name: "kill etcd instances"
  shell: killall etcd
  ignore_errors: yes
  become: yes
  tags:
    - driver
    - site

- name: "kill golang instances"
  shell: killall golang
  ignore_errors: yes
  become: yes
  tags:
    - driver
    - site


- name: Enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  when: ansible_distribution == "Fedora"

- name: Set dmz as default policy
  command: firewall-cmd --set-default-zone=public
  when: ansible_distribution == "Fedora"

- name: (fedora) add etcd firewalld rule
  firewalld:
    zone: public
    port: 2379-2380/tcp
    source: 10.0.0.0/24
    permanent: true
    immediate: true
    state: enabled
  become: yes
  tags:
    - database
    - site
  when: ansible_distribution == "Fedora"

- name: flush iptable rules
  iptables:
    flush: yes
  tags:
    - driver
    - site
  when: ansible_distribution == "Ubuntu"

- name: add etcd iptable rule
  iptables:
    chain: INPUT
    in_interface: eth1
    protocol: tcp
    source: 10.0.0.0/24
    destination_port: 2379:2380
    jump: ACCEPT
  become: yes
  tags:
    - driver
    - site
  when: ansible_distribution == "Ubuntu"

- name: copy host file to driver
  template:
    src: roles/driver/templates/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  become: yes
  tags:
    - driver
    - site

- name: create go stuff
  file:
    path: /root/go/src/gitlab.com/mergetb/
    owner: root
    group: root
    state: directory
    mode: 0775
  become: yes
  tags:
    - driver
    - site

- name: get latest driver code
  git:
    repo: 'https://gitlab.com/dcomptb/agents.git'
    dest: /root/go/src/gitlab.com/dcomptb/agents
    clone: yes
    update: yes
  become: yes
  tags:
    - driver
    - site

- name: get go-protobuf
  shell: go get github.com/ceph/go-ceph
  environment:
    GOPATH: /root/go/
    GOBIN: /root/go/bin
    GOROOT: /root/gosrc/go
  become: yes
  tags:
    - driver
    - site

- name: get go-protobuf
  shell: go get -u github.com/golang/protobuf/protoc-gen-go
  environment:
    GOPATH: /root/go/
    GOBIN: /root/go/bin
    GOROOT: /root/gosrc/go
  become: yes
  tags:
    - driver
    - site

- name: get dep
  shell: go get -u github.com/golang/dep/cmd/dep
  environment:
    GOPATH: /root/go/
    GOROOT: /root/gosrc/go
  become: yes
  tags:
    - driver
    - site

- name: dep ensure
  shell: $GOBIN/dep ensure -v
  args:
    chdir: /root/go/src/gitlab.com/dcomptb/agents
  environment:
    GOPATH: /root/go/
    GOROOT: /root/gosrc/go
    GOBIN: /root/go/bin
  become: yes
  tags:
    - driver
    - site

- name: set path variable
  set_fact:
    path_var:  "{{ lookup('env','PATH') }}"
  tags:
    - driver
    - site

- name: make driver
  make:
    chdir: /root/go/src/gitlab.com/dcomptb/agents/node
    target: all
  become: yes
  environment:
    GOPATH: /root/go/
    GOROOT: /root/gosrc/go
    PATH: "{{ path_var }}:/root/go/bin"
  tags:
    - driver
    - site

- name: move driver to /usr/bin
  copy:
    src: /root/go/src/gitlab.com/dcomptb/agents/node/build/driver
    dest: /usr/bin/driver
    mode: 0755
    remote_src: yes
  become: yes
  tags:
    - driver
    - site

- name: copy systemd file to driver
  template:
    src: roles/driver/templates/josephine.service.j2
    dest: /etc/systemd/system/josephine.service
    owner: root
    group: root
  become: yes
  tags:
    - driver
    - site

- name: start driver (josephine) service
  systemd:
    state: started
    enabled: True
    name: josephine
  tags:
    - driver
    - site

- name: restart driver (josephine) to pick up daemon changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: josephine
  tags:
    - driver
    - site
